### ISSUE TITLE
AttributeError: partially initialized module 'gif' has no attribute 'options' (most likely due to a circular import)

### ISSUE THREAD

**Issue by jvallef** [maxhumber/gif#13]
Hi, using gif-22.5.0 for the first time...

macOS 12.4
python 3.9.12

Running example at Usage point in https://pypi.org/project/gif/

```
(.pepito) jose@MacBook-Air-2 keynote % python3 gif.py
Traceback (most recent call last):
  File "/Users/jose/Web/keynote/gif.py", line 3, in <module>
    import gif
  File "/Users/jose/Web/keynote/gif.py", line 9, in <module>
    gif.options.matplotlib["dpi"] = 300
AttributeError: partially initialized module 'gif' has no attribute 'options' (most likely due to a circular import)
```

**Comment by maxhumber** [comment]
Closing as I've been unable to replicate... Please reopen if the error persists!
